# Generated by Django 3.1.14 on 2022-09-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20220925_0631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
