# Generated by Django 3.1.14 on 2022-09-25 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contentshub', '0004_auto_20220925_1622'),
        ('community', '0003_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_klass', to='contentshub.klass')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='community.question')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
