# Generated by Django 3.1.14 on 2022-09-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='contents',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='contents',
            new_name='content',
        ),
    ]
