# Generated by Django 3.1.14 on 2022-09-25 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentshub', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klass', to='contentshub.klass'),
        ),
    ]
